/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonianzeRouteImport } from './routes/testimonianze'
import { Route as ScrittiRouteImport } from './routes/scritti'
import { Route as IlCamminoRouteImport } from './routes/il-cammino'
import { Route as EsperienzeRouteImport } from './routes/esperienze'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSonoRouteImport } from './routes/chi-sono'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScrittiSlugRouteImport } from './routes/scritti.$slug'

const TestimonianzeRoute = TestimonianzeRouteImport.update({
  id: '/testimonianze',
  path: '/testimonianze',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrittiRoute = ScrittiRouteImport.update({
  id: '/scritti',
  path: '/scritti',
  getParentRoute: () => rootRouteImport,
} as any)
const IlCamminoRoute = IlCamminoRouteImport.update({
  id: '/il-cammino',
  path: '/il-cammino',
  getParentRoute: () => rootRouteImport,
} as any)
const EsperienzeRoute = EsperienzeRouteImport.update({
  id: '/esperienze',
  path: '/esperienze',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSonoRoute = ChiSonoRouteImport.update({
  id: '/chi-sono',
  path: '/chi-sono',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScrittiSlugRoute = ScrittiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ScrittiRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/esperienze': typeof EsperienzeRoute
  '/il-cammino': typeof IlCamminoRoute
  '/scritti': typeof ScrittiRouteWithChildren
  '/testimonianze': typeof TestimonianzeRoute
  '/scritti/$slug': typeof ScrittiSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/esperienze': typeof EsperienzeRoute
  '/il-cammino': typeof IlCamminoRoute
  '/scritti': typeof ScrittiRouteWithChildren
  '/testimonianze': typeof TestimonianzeRoute
  '/scritti/$slug': typeof ScrittiSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chi-sono': typeof ChiSonoRoute
  '/contatti': typeof ContattiRoute
  '/esperienze': typeof EsperienzeRoute
  '/il-cammino': typeof IlCamminoRoute
  '/scritti': typeof ScrittiRouteWithChildren
  '/testimonianze': typeof TestimonianzeRoute
  '/scritti/$slug': typeof ScrittiSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-sono'
    | '/contatti'
    | '/esperienze'
    | '/il-cammino'
    | '/scritti'
    | '/testimonianze'
    | '/scritti/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chi-sono'
    | '/contatti'
    | '/esperienze'
    | '/il-cammino'
    | '/scritti'
    | '/testimonianze'
    | '/scritti/$slug'
  id:
    | '__root__'
    | '/'
    | '/chi-sono'
    | '/contatti'
    | '/esperienze'
    | '/il-cammino'
    | '/scritti'
    | '/testimonianze'
    | '/scritti/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiSonoRoute: typeof ChiSonoRoute
  ContattiRoute: typeof ContattiRoute
  EsperienzeRoute: typeof EsperienzeRoute
  IlCamminoRoute: typeof IlCamminoRoute
  ScrittiRoute: typeof ScrittiRouteWithChildren
  TestimonianzeRoute: typeof TestimonianzeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonianze': {
      id: '/testimonianze'
      path: '/testimonianze'
      fullPath: '/testimonianze'
      preLoaderRoute: typeof TestimonianzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scritti': {
      id: '/scritti'
      path: '/scritti'
      fullPath: '/scritti'
      preLoaderRoute: typeof ScrittiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/il-cammino': {
      id: '/il-cammino'
      path: '/il-cammino'
      fullPath: '/il-cammino'
      preLoaderRoute: typeof IlCamminoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esperienze': {
      id: '/esperienze'
      path: '/esperienze'
      fullPath: '/esperienze'
      preLoaderRoute: typeof EsperienzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-sono': {
      id: '/chi-sono'
      path: '/chi-sono'
      fullPath: '/chi-sono'
      preLoaderRoute: typeof ChiSonoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scritti/$slug': {
      id: '/scritti/$slug'
      path: '/$slug'
      fullPath: '/scritti/$slug'
      preLoaderRoute: typeof ScrittiSlugRouteImport
      parentRoute: typeof ScrittiRoute
    }
  }
}

interface ScrittiRouteChildren {
  ScrittiSlugRoute: typeof ScrittiSlugRoute
}

const ScrittiRouteChildren: ScrittiRouteChildren = {
  ScrittiSlugRoute: ScrittiSlugRoute,
}

const ScrittiRouteWithChildren =
  ScrittiRoute._addFileChildren(ScrittiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiSonoRoute: ChiSonoRoute,
  ContattiRoute: ContattiRoute,
  EsperienzeRoute: EsperienzeRoute,
  IlCamminoRoute: IlCamminoRoute,
  ScrittiRoute: ScrittiRouteWithChildren,
  TestimonianzeRoute: TestimonianzeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
